export const getSectionStyles = (path = "section.style") => [
  { path: `${path}.backgroundColor`, label: "رنگ پس‌زمینه", type: "color" },
  { path: `${path}.color`, label: "رنگ متن کل", type: "color" },
  {
    path: `${path}.fontFamily`,
    label: "فونت",
    type: "dropdown",
    options: [
      "Anjoman",
      "IRANSansX",
      "IRANYekan",
      "Rokh",
      "Shabnam",
      "Vazir",
      "Vazirmatn",
    ],
  },
  {
    path: `${path}.fontSize`,
    label: "سایز پایه",
    type: "slider",
    min: 12,
    max: 32,
    unit: "px",
  },
  {
    path: `${path}.lineHeight`,
    label: "ارتفاع خط",
    type: "slider",
    min: 1,
    max: 3,
    step: 0.1,
  },
  { path: `${path}.padding`, label: "فاصله داخلی (Padding)", type: "text" },
  { path: `${path}.margin`, label: "فاصله خارجی (Margin)", type: "text" },
];

export const getTypographyControls = (path, labelPrefix = "") => [
  {
    path: `${path}.content.text`,
    label: `متن ${labelPrefix}`,
    type: "textarea",
  },
  { path: `${path}.content.url`, label: "لینک", type: "url" },
  { path: `${path}.style.color`, label: "رنگ متن", type: "color" },
  {
    path: `${path}.style.backgroundColor`,
    label: "رنگ پس‌زمینه",
    type: "color",
  },
  {
    path: `${path}.style.fontFamily`,
    label: "فونت",
    type: "dropdown",
    options: [
      "Anjoman",
      "IRANSansX",
      "IRANYekan",
      "Rokh",
      "Shabnam",
      "Vazir",
      "Vazirmatn",
    ],
  },
  {
    path: `${path}.style.fontSize`,
    label: "سایز فونت",
    type: "slider",
    min: 10,
    max: 100,
    unit: "px",
  },
  {
    path: `${path}.style.lineHeight`,
    label: "ارتفاع خط",
    type: "slider",
    min: 1,
    max: 3,
    step: 0.1,
  },
  {
    path: `${path}.style.fontWeight`,
    label: "ضخامت",
    type: "dropdown",
    options: ["normal", "bold", "100", "300", "500", "900"],
  },
  { path: `${path}.style.textAlign`, label: "چیدمان متن", type: "alignment" },
];

export const getButtonControls = (path, labelPrefix = "دکمه") => [
  { path: `${path}.content.text`, label: `متن ${labelPrefix}`, type: "text" },
  { path: `${path}.content.url`, label: `لینک ${labelPrefix}`, type: "url" },
  { path: `${path}.style.color`, label: "رنگ متن", type: "color" },
  {
    path: `${path}.style.backgroundColor`,
    label: "رنگ پس‌زمینه",
    type: "color",
  },
  {
    path: `${path}.style.fontFamily`,
    label: "فونت",
    type: "dropdown",
    options: [
      "Anjoman",
      "IRANSansX",
      "IRANYekan",
      "Rokh",
      "Shabnam",
      "Vazir",
      "Vazirmatn",
    ],
  },
  {
    path: `${path}.style.fontSize`,
    label: "سایز فونت",
    type: "slider",
    min: 10,
    max: 50,
    unit: "px",
  },
  {
    path: `${path}.style.lineHeight`,
    label: "ارتفاع خط",
    type: "slider",
    min: 1,
    max: 3,
    step: 0.1,
  },
  {
    path: `${path}.style.borderRadius`,
    label: "گردی گوشه‌ها",
    type: "slider",
    min: 0,
    max: 50,
    unit: "px",
  },
  { path: `${path}.style.border`, label: "حاشیه (Border)", type: "text" },
  {
    path: `${path}.hover.backgroundColor`,
    label: "رنگ پس‌زمینه (هاور)",
    type: "color",
  },
  { path: `${path}.hover.color`, label: "رنگ متن (هاور)", type: "color" },
];
